export const styles = {
    
  // ── Layout ──────────────────────────────────────────────
  header: {
    background: "#fff",
    borderBottom: "1px solid #e8e3dc",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  
headerInner: {
  width: "100%",
  padding: "14px 24px",
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 16,
},
  logo: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 20,
    fontWeight: 700,
    color: "#1a1a1a",
  },
  logoSub: { fontSize: 11, color: "#999", marginTop: 1 },
  headerActions: { display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" },
  headerCall: {
    fontSize: 13,
    fontWeight: 500,
    color: "#1a1a1a",
    display: "flex",
    alignItems: "center",
    gap: 4,
    textDecoration: "none",
  },
  sellBtn: {
    background: "#1a1a1a",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },

  // ── Hero ─────────────────────────────────────────────────
  hero: {
    background: "linear-gradient(135deg, #1c2b1c 0%, #2d4a2d 60%, #1a3a2a 100%)",
    color: "#fff",
    padding: "64px 24px",
  },
  heroEye: {
    fontSize: 12,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "#8fbc8f",
    marginBottom: 16,
  },
  heroH1: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "clamp(28px, 5vw, 48px)",
    lineHeight: 1.2,
    marginBottom: 16,
  },
  heroSub: {
    fontSize: 15,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.7,
    marginBottom: 28,
    maxWidth: 500,
  },
  heroBadges: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 24 },
  areaBadge: {
    fontSize: 11,
    background: "rgba(255,255,255,0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "rgba(255,255,255,0.8)",
    padding: "4px 10px",
    borderRadius: 20,
  },

  // ── Filter Bar ───────────────────────────────────────────
  filterBar: { background: "#fff", borderBottom: "1px solid #e8e3dc", padding: "12px 24px" },
  filterInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    gap: 16,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  filterBtn: {
    fontSize: 13,
    padding: "6px 14px",
    borderRadius: 20,
    border: "1px solid #ddd",
    background: "none",
    cursor: "pointer",
    color: "#555",
  },
  filterActive: { background: "#1a1a1a", color: "#fff", border: "1px solid #1a1a1a" },
  select: {
    fontSize: 13,
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid #ddd",
    background: "#fff",
    cursor: "pointer",
    color: "#333",
  },

  // ── Listings Grid ────────────────────────────────────────
  main: { width: "100%", maxWidth: 1600, margin: "0 auto", padding: "28px 24px 48px" },
  resultsInfo: { marginBottom: 20, fontSize: 14, color: "#666", display: "flex", alignItems: "center" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 24 },

  // ── Property Card ────────────────────────────────────────
  card: {
    background: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  cardTop: { padding: "22px 20px 18px", color: "#fff", position: "relative" },
  cardTitle: { fontFamily: "'Playfair Display', serif", fontSize: 18, marginTop: 10, marginBottom: 4 },
  cardArea: { fontSize: 12, opacity: 0.75 },
  priceTag: {
    position: "absolute",
    top: 16,
    right: 16,
    fontSize: 15,
    fontWeight: 700,
    background: "rgba(255,255,255,0.15)",
    padding: "4px 10px",
    borderRadius: 6,
    backdropFilter: "blur(4px)",
  },
  cardBody: { padding: "18px 20px 20px" },

  // ── Shared UI ────────────────────────────────────────────
  badge: {
    display: "inline-block",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#fff",
    padding: "3px 8px",
    borderRadius: 4,
  },
  specs: { display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  spec: { fontSize: 12, color: "#555", background: "#f5f2ee", padding: "3px 8px", borderRadius: 4 },
  tag: { fontSize: 11, color: "#6a7a6a", background: "#eef3ee", padding: "3px 8px", borderRadius: 4 },
  primaryBtn: {
    background: "#1a1a1a",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    display: "inline-block",
    textDecoration: "none",
  },
  callBtn: {
    display: "inline-block",
    border: "1.5px solid #ddd",
    borderRadius: 7,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 500,
    color: "#333",
    cursor: "pointer",
    textDecoration: "none",
    background: "#fff",
  },

  // ── Sell Banner ──────────────────────────────────────────
  sellBanner: {
    background: "linear-gradient(135deg, #2d4a2d, #1c3a2c)",
    color: "#fff",
    padding: "56px 24px",
  },

  // ── Footer ───────────────────────────────────────────────
  footer: { background: "#111", color: "#aaa", padding: "36px 24px", textAlign: "center" },

  // ── Modal ────────────────────────────────────────────────
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
  },
  modal: {
    background: "#fff",
    borderRadius: 14,
    padding: "28px 28px 24px",
    width: "100%",
    maxWidth: 420,
    maxHeight: "90vh",
    overflowY: "auto",
    position: "relative",
  },
  closeBtn: {
    position: "absolute",
    top: 14,
    right: 16,
    background: "none",
    border: "none",
    fontSize: 16,
    cursor: "pointer",
    color: "#999",
  },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#555",
    marginBottom: 5,
    letterSpacing: "0.04em",
  },
  input: {
    width: "100%",
    border: "1.5px solid #e0dbd4",
    borderRadius: 7,
    padding: "9px 12px",
    fontSize: 14,
    outline: "none",
    background: "#faf9f7",
    fontFamily: "inherit",
  },
};